---
- hosts: all
  remote_user: root
  tasks:
  - name: gcc and debuginfo rpms
    yum:
      name:
        - bind-utils
        - gcc
        - gdb
        - gnutls-utils
        - epel-release
        - lsof
        - ltrace
        - mtr
        - nc
        - python3-pip
        - strace
        - tmux
        - traceroute
      state: present

  - name: Install htop
    yum:
      name:
        - htop
      state: present
      update_cache: true

  - name: asciinema playback
    shell: pip3 install asciinema

  - name: debuginfo install
    shell: debuginfo-install -y glibc-common bzip2-libs elfutils-libelf elfutils-libs libattr libcap libgcc systemd-libs python xz-libs zlib || exit 0

  - name: bashrc updates
    copy:
      src:  ./getip.sh
      dest: /etc/profile.d/getip.sh
  - name: set limits on user foo
    copy:
      src: ./30-foo.conf
      dest: /etc/security/limits.d/30-foo.conf
  - name: hosts entry for getip_hostname
    lineinfile:
      dest: /etc/hosts
      line: "1.1.1.1     getip_hostname"
      state: present
  - name: hosts entry for google.com
    lineinfile:
      dest: /etc/hosts
      line: "1.2.3.4     lisa2019"
      state: present
  - name: foo group
    group:
      name: foo

  - name: foo user (limits demo)
    user:
      name: foo
      comment: Foo Bar
      uid: 1040
      group: foo
  - name: lisa2019 user (nss demo)
    copy:
      src: ./lisa2019.user
      dest: /etc/passwd.db 
  - name: update makedb Makefile (nss demo)
    lineinfile:
      dest: /var/db/Makefile
      regexp: '^$(VAR_DB)/passwd.db'
      line: '$(VAR_DB)/passwd.db: /etc/passwd.db'
      state: present
  - name: run makedb to update nss_db (nss demo)
    shell: cd /var/db; make
  - name: update nsswitch.conf for nss_db (nss demo)
    lineinfile:
      dest: /etc/nsswitch.conf
      regexp: '^passwd:'
      line: 'passwd:     db files sss'
      state: present
